ENVIRONMENT:
  # MAX_EPISODE_STEPS: 1500
  MAX_EPISODE_STEPS: 500
SIMULATOR:
  FORWARD_STEP_SIZE: 0.25
  TURN_ANGLE: 10
  AGENT_0:
    # HEIGHT: 0.88
    # RADIUS: 0.18
    SENSORS: ['DEPTH_SENSOR']
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: True
  RGB_SENSOR:
    WIDTH: 256
    HEIGHT: 256
  DEPTH_SENSOR:
    WIDTH: 256
    HEIGHT: 256
  ACTION_SPACE: 'DISCRETE'
  ACTION_DISTRIBUTION: 'CATEGORICAL'
  NUM_ACTION_INCREMENTS: '2'
TASK:
  TYPE: Nav-v0
  SUCCESS_DISTANCE: 0.2

  SENSORS: ['POINTGOAL_WITH_GPS_COMPASS_SENSOR']
  POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    GOAL_FORMAT: "POLAR"
    DIMENSIONALITY: 2
  GOAL_SENSOR_UUID: pointgoal_with_gps_compass

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL', 'SCT']
  SPL:
    TYPE: SPL
    SUCCESS_DISTANCE: 0.2
  SCT:
    TYPE: SCT
DATASET:
  TYPE: PointNav-v1
  SPLIT: train
  # DATA_PATH: data/{split}/{split}.json.gz
  # DATA_PATH: /nethome/nyokoyama3/n/datasets/pointnav_gibson/v2/{split}/{split}.json.gz
  # DATA_PATH: /nethome/nyokoyama3/n/datasets/pointnav_gibson/v2_bc/{split}/{split}.json.gz
  DATA_PATH: /srv/datasets/habitat-sim-datasets/pointnav/gibson/v1/{split}/{split}.json.gz